### ISSUE TITLE
TODO Count 3/ FIXME Count 1

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-vue-credential-card#31]
- [ ] TODO: specify propsData
       Commit: (f167eb4) Add core files.
       Fi[test/web/10-CredentialCard.js:15](https://github.com/digitalbazaar/bedrock-vue-credential-card/blob/master/test/web/10-CredentialCard.js#L15)
       Dave Longley commented 2 years ago

  - [ ] TODO: consider moving to `bedrock-karma`?
       Commit: (e891561) Fix test config and add postinstall script.
       File:  [test/test.config.js:12](https://github.com/digitalbazaar/bedrock-vue-credential-card/blob/master/test/test.config.js#L12)
       Dave Longley commented 2 years ago

  - [ ] FIXME: make configurable
       Commit: (f167eb4) Add core files.
       File:  [test/components/index.js:10](https://github.com/digitalbazaar/bedrock-vue-credential-card/blob/master/test/components/index.js#L10)
       Dave Longley commented 2 years ago

  - [ ] TODO: $vm.el.something
       Commit: (f167eb4) Add core files.
       Fi[test/web/10-CredentialCard.js:27](https://github.com/digitalbazaar/bedrock-vue-credential-card/blob/master/test/web/10-CredentialCard.js#L27)
       Dave Longley commented 2 years ago

       TODO Count          3
       FIXME Count         1
       Oldest Comment      2 years ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: specify propsData
